name: Auto push files 
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./push_it.sh
         ./push_it.sh
      shell: bash
