name: Auto push files 

on:
  schedule:
    # Triggers the workflow every 5 minutes
    - cron: '*/5 * * * *'
jobs:
  autopush:
    name: Trigger auto push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Append random line
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/touch_it.sh"
        "${GITHUB_WORKSPACE}/.github/script.sh"
      shell: bash
    - name: Auto commit changes 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto commit
