name: Auto push files 

on:
  schedule:
    # Triggers the workflow every 5 minutes
    - cron: '*/5 * * * *'
jobs:
  autopush:
    name: Trigger auto push
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Run script file
    - uses: actions/checkout@master
      run: |
         chmod +x ./touch_it.sh
         ./touch_it.sh
      shell: bash

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto commit
